version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - /var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
      - "DB_PORT=3306"
    container_name: complaints_application

# The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
        - "${LE_DIR}:/etc/letsencrypt"
    ports:
        - 8080:80
        - 443:443
    container_name: nginx_server

# The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  
  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: