version: '2'
services:


# The Web Server
  web:
    build:
      context: ./
      dockerfile: dockerfiles/web.dockerfile
    ports:
        - 8080:80
    container_name: nginx_server

# The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
  
  # redis
  cache:
    image: redis:3.0-alpine

  # The Application
  app:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ./app:/var/www/app
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
      - "DB_PORT=3306"
    container_name: complaints_application

volumes:
  dbdata: