version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    volumes:
        - ./app:/var/www/app
        - ./resources:/var/www/resources
        - ./database:/var/www/database
        - ./public:/var/www/public
        - ./routes:/var/www/routes
        - ./tests:/var/www/tests
    env_file: '.env.prod'
    environment:
      - "DB_HOST=db"
      - "REDIS_HOST=cache"
      - "DB_PORT=3306"
    container_name: complaints-application

  web:
    build:
      context: ./
      dockerfile: dockerfiles/web.dockerfile
    volumes:
        - ./logs:/var/log/nginx
        - ./public:/var/www/public       
        - ./default.conf:/etc/nginx/sites-available/default
        - ./default.conf:/etc/nginx/sites-enabled/default
    ports:
        - 3010:80
    container_name: nginx-server

  db:
    image: mysql:5.6
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file: '.env.prod'
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    container_name: complaints-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
        - db
    ports:
        - "3011:80"
    container_name: complaints-pma

